export const routers = {
  root: "/",
  profile: "/profile/:id",
  article: "/article/:id",
  createArticle: "/article/create",
  editArticle: "/article/edit/:id",
  contacts: "/contacts",
  about: "/about",
  login: "/login",
  signup: "/signup",
  admin: "/admin",
  adminArticles: "/admin/articles",
  adminComments: "/admin/comments",
  adminUsers: "/admin/users",
};
